version: 2.1

jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Build frontend
          command: |
            cd ./frontend
            npm i
            npm run build

workflows:
    jobs:
      - build-frontend